name: 'Receive event from another workflow'
on:
  repository_dispatch:
    types: [functional-tests-approved]
  workflow_dispatch:
jobs:
  preprocess:
    name: Pre-process for functional tests
    runs-on: ubuntu-latest
    outputs:
      TRIGGER: ${{ steps.trigger.outputs.TRIGGER }}
      SKIP_FUNCTIONAL_TESTS: ${{ steps.trigger.outputs.SKIP_FUNCTIONAL_TESTS }}
    steps:
      - name: Determine trigger of workflow
        id: trigger
        env:
          REPOSITORY : ${{ github.repository }}
          EVENT_NAME: ${{ github.event_name }}
          EVENT_TYPE: ${{ github.event.action }}
          ONLY_VERSIONS_CHANGED: ${{ github.event.client_payload.versionsChangedOnly }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_ACTION_DISPATCH }}
          script: |
            let fs = require('fs');
            let trigger = 'unknown';
            let skipFuncTests = false;

            console.log('Event name: ' + process.env.EVENT_NAME);
            console.log('Event type: ' + process.env.EVENT_TYPE);
            console.log('Repository: ' + process.env.REPOSITORY);
            console.log('Only versions changed: ' + process.env.ONLY_VERSIONS_CHANGED);
            
            if (process.env.EVENT_NAME === 'workflow_dispatch' && process.env.REPOSITORY === 'lechnerc77/ghaction-testing') {
              trigger = 'dispatch'
            }

            if (process.env.EVENT_NAME === 'repository_dispatch' && process.env.EVENT_TYPE === 'de-functional-test') {
              trigger = 'de-functional-test'
            }

            if (process.env.EVENT_NAME === 'repository_dispatch' && process.env.EVENT_TYPE === 'functional-tests-approved') {
              trigger = 'functional-tests-approved'

              if (process.env.ONLY_VERSIONS_CHANGED === 'true') {
                skipFuncTests = true

                console.log('Only versions.yaml changed. Skipping functional tests.')
              }
            }

            fs.appendFileSync(process.env.GITHUB_ENV,
              `TRIGGER=${trigger}\n`+
              `SKIP_FUNCTIONAL_TESTS=${skipFuncTests}`
            );
  
  execute-functional-tests-run:
    name: 'Approve Functional Tests'
    runs-on: ubuntu-latest
    needs: preprocess
    if: needs.preprocess.outputs.SKIP_FUNCTIONAL_TESTS == 'false'
    env:
      TRIGGER: ${{ needs.preprocess.outputs.TRIGGER }}
    steps:
    - name: Execute dispatch
      if: env.TRIGGER == 'dispatch'
      run: |
        echo workflow was manually dispatched
    - name: Execute trigger
      if: env.TRIGGER == 'functional-tests-approved'
      run: |
          echo workflow was externally triggered
        