name: 'Receive event from another workflow'
on:
  repository_dispatch:
    types: [functional-tests-approved]
  workflow_dispatch:
jobs:
  preprocess:
    name: Pre-process for functional tests
    runs-on: ubuntu-latest
    outputs:
      TRIGGER: ${{ steps.trigger.outputs.TRIGGER }}
      SKIP_FUNCTIONAL_TESTS: ${{ steps.trigger.outputs.SKIP_FUNCTIONAL_TESTS }}
    steps:
      - name: Determine trigger of workflow
        id: trigger
        env:
          REPOSITORY : ${{ github.repository }}
          EVENT_NAME: ${{ github.event_name }}
          EVENT_TYPE: ${{ github.event.action }}
          ONLY_VERSIONS_CHANGED: ${{ github.event.client_payload.versionsChangedOnly }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_ACTION_DISPATCH }}
          script: |
            let trigger = 'unknown';
            let skipFuncTests = false;

            if (process.env.EVENT_NAME === 'workflow_dispatch' && process.env.REPOSITORY === 'lechnerc77/ghaction-testing') {
              trigger = 'dispatch'
            }

            if (process.env.EVENT_NAME === 'repository_dispatch' && process.env.EVENT_TYPE === 'de-functional-test') {
              trigger = 'de-functional-test'
            }

            if (process.env.EVENT_NAME === 'repository_dispatch' && process.env.EVENT_TYPE === 'functional-tests-approved') {
              trigger = 'functional-tests-approved'

              if (process.env.ONLY_VERSIONS_CHANGED === 'true') {
                skipFuncTests = true

                console.log('Only versions.yaml changed. Skipping functional tests.')
              }
            }

            core.setOutput('TRIGGER', trigger);
            core.setOutput('SKIP_FUNCTIONAL_TESTS', skipFuncTests);
  
  check-output:
    name: 'Check output'
    runs-on: ubuntu-latest
    needs: preprocess
    env:
      TRIGGER: ${{ needs.preprocess.outputs.TRIGGER }}
      SKIP_TESTS: ${{ needs.preprocess.outputs.SKIP_FUNCTIONAL_TESTS }}
    steps:
    - name: Display output
      run: |
        echo Trigger: ${{ env.TRIGGER }}
        echo Skip functional tests: ${{ env.SKIP_TESTS }}
                            

  execute-functional-tests-run:
    name: 'Approve Functional Tests'
    runs-on: ubuntu-latest
    needs: [preprocess, check-output]
    if: needs.preprocess.outputs.SKIP_FUNCTIONAL_TESTS == 'false'
    env:
      TRIGGER: ${{ needs.preprocess.outputs.TRIGGER }}
    steps:
    - name: Execute dispatch
      if: env.TRIGGER == 'dispatch'
      run: |
        echo workflow was manually dispatched
    - name: Execute trigger
      if: env.TRIGGER == 'functional-tests-approved'
      run: |
          echo workflow was externally triggered
        