name: 'Receive event from another workflow'
on:
  repository_dispatch:
    types: [run-functional-tests]
jobs:
  execute-functional-tests-run:
    name: 'Approve Functional Tests'
    runs-on: ubuntu-latest
    steps:
    - name: Try to run functional tests
      if: github.event_name == 'repository_dispatch'
      run: |
        echo triggering event type - ${{ github.event.action }}
        echo value of version change ${{ github.event.client_payload.versionChanged }}
        